### ISSUE TITLE
RFC: Use MediaWiki

### ISSUE THREAD

**Issue by ElijahPepe** [steamdeck-linux/wiki#6]
While the open source nature of the wiki as it is may have to be severely limited by MediaWiki, the wiki could benefit greatly from an [open-source](https://phabricator.wikimedia.org/diffusion/) and [widely used](https://en.wikipedia.org/wiki/MediaWiki) software. In my opinion, a web-based solution would be far better due to its accessibility (if we want to expand, getting to the broadest possible audience is key).

I'm opening this RFC to gauge interest. While it can't be run via GH Pages, the benefits vastly outweigh the costs based on what I've seen from MW.

**Comment by moxvallix** [comment]
Yeah I have been thinking about using Media Wiki, as Wikipedia is a familiar format, and also web based editing is a major plus. I'll see what I can do about setting one up.

**Comment by ElijahPepe** [comment]
If you set one up, please be incredibly aware that this GitHub repository would serve little to no purpose. MW itself does not work off of open-source in the traditional sense; most wikis don't even have open repositories because they aren't large enough to warrant custom additions and changes. If you do end up uploading MW files here, avoid uploading the LocalSettings.php file as it would contain your MySQL database information and the administrator username + password.

**Comment by moxvallix** [comment]
Don't worry, this repo was only set up to use the Zim with. Now I have a mediawiki, it's unlikely this will be used for much now. Check it out here: https://steamdeck.miraheze.org/

**Comment by ElijahPepe** [comment]
Miraheze isn't a good MW host. Very slow and has limiting options in regards on how you should set it up, and from what I've heard has a notorious reputation as being the provider of the "Reception Wikis" which itself have their own drama and insane community. My personal idea was using a domain like steamdeck.wiki (which is somehow registered?) with a cheap VPS.

**Comment by moxvallix** [comment]
I'll stick with them for now, as it all seems to be working fine for me. If issues arise we can always export it and relocate. I was surprised that steamdeck.wiki was taken as well; thinking of maybe going with steamdecklinux.wiki.

**Comment by ElijahPepe** [comment]
Closed due to using MW (albeit the host I will vehemently protest against).
